/// <autosync enabled="true" />
/// <reference path="bootstrap.js" />
/// <reference path="jquery-1.9.1.js" />
/// <reference path="../personctrl.js" />
/// <reference path="../app10-isolate-scope-=/main.js" />
/// <reference path="../app01-binding/main.js" />
/// <reference path="../app02-filters/main.js" />
/// <reference path="../app03-directives/main.js" />
/// <reference path="../app05-directives-controllers/main.js" />
/// <reference path="../app06-directive-directive/main.js" />
/// <reference path="../app07-templates/main.js" />
/// <reference path="../app08-isolate-scope/main.js" />
/// <reference path="../app09-isolate-scope-@/main.js" />
/// <reference path="../app11-isolate-scope-ampersand/main.js" />
/// <reference path="../app12-isolate-scope-review/main.js" />
/// <reference path="../app13-transclusion/main.js" />
/// <reference path="../app14-alternative controllers/main.js" />
/// <reference path="../app15-organisation/main.js" />
/// <reference path="../app14-alternative controllers/main2.js" />
/// <reference path="../app16-zippy/main.js" />
/// <reference path="../app17-elements/main.js" />
/// <reference path="../app18-values and constants/main.js" />
/// <reference path="../app19-$scope vs scope/main.js" />
/// <reference path="../app20-templateurl/main.js" />
/// <reference path="../app21-templatecache/main.js" />
/// <reference path="../app22-ng-view/main.js" />
/// <reference path="angular-route.js" />
/// <reference path="../app23-route-params/main.js" />
/// <reference path="../app24-promises/main.js" />
/// <reference path="../app24-resolve/main.js" />
/// <reference path="../app26-components-containers/main.js" />
/// <reference path="../app25-providers/main.js" />
/// <reference path="../app27-ng-repeat/main.js" />
/// <reference path="../app28-directive-communication/main.js" />
/// <reference path="angular-mocks.js" />
/// <reference path="angular.js" />
/// <reference path="angular-animate.js" />
/// <reference path="../app29-controlleras/main.js" />
/// <reference path="../app30-animation-basics/main.js" />
