/// <autosync enabled="true" />
/// <reference path="angular-mocks.js" />
/// <reference path="angular.js" />
/// <reference path="bootstrap.js" />
/// <reference path="jquery-1.9.1.js" />
/// <reference path="../personctrl.js" />
/// <reference path="../app10-isolate-scope-=/main.js" />
/// <reference path="../app01-binding/main.js" />
/// <reference path="../app02-filters/main.js" />
/// <reference path="../app03-directives/main.js" />
/// <reference path="../app05-directives-controllers/main.js" />
/// <reference path="../app06-directive-directive/main.js" />
/// <reference path="../app07-templates/main.js" />
/// <reference path="../app08-isolate-scope/main.js" />
/// <reference path="../app09-isolate-scope-@/main.js" />
/// <reference path="../app11-isolate-scope-ampersand/main.js" />
